### PR TITLE
BK-6496: adding a method to update headers

### PR DESCRIPTION
**Pull request by hod-stratoscale**

### CODE REVIEW

**Comment by sharbov** [comment]
ok, I guess.

Can you explain what is this for ?

**Comment by hod-stratoscale** [comment]
> ok, I guess.
> 
> Can you explain what is this for ?

in order to implement internal resources headers we need a way to change the credentials after the client is created because we the managing_resource_id in lbaas for example is created after i'ts clients created @sharbov

**Comment by spellr** [comment]
@ravidbro but it does only add..

**Comment by ravidbro** [comment]
sorry, my bad

**Pull request merged**
