### PR TITLE
BK-6997: httplib doesn't exist in python3

### PR DESCRIPTION
**Pull request by spellr**

### CODE REVIEW

**Comment by ravidbro** [comment]
@spellr we know that hammock doesn't support python 3, there are few more places that need to be changed.
On which service do we want to use or already using python3?

**Comment by spellr** [comment]
@ravidbro IAM :)

**Comment by spellr** [comment]
@ravidbro AFAIK, hammock supposed to support python3

**Comment by rom-stratoscale** [comment]
why do we use python3?

**Comment by spellr** [comment]
This is what's been used by aws-api-common

**Comment by ravidbro** [comment]
Looks like IAM already using Flask and not aio like all the other services, I think it's just a matter of changing the base image.
I remember that we decided in the past to transition the few services of python3 to python2 and put the effort on GO instead of a third language

**Comment by ravidbro** [comment]
aws-api-common is a library, not a service and it's not relying on python3 because we have a lot of python2 services that are using that library

**Comment by spellr** [comment]
Yes, it's not relying on python3, but IAM is running with python3, so we
need the libraries it imports to support it as well. I didn't really try to
change the base image, in this case, making hammock compatible was easier

**Pull request merged**
